name: "Documentation"

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  documentation:
    name: "Documentation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Build"
        uses: "phpDocumentor/phpDocumentor@v3.5.3"
        with:
          target: "docs/build"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
